apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: julia
  namespace: iterate
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
  - name: clusterBuilder
    value: julia-builder
  source:
    git:
      ref:
        branch: main
      url: https://github.com/timosalm/julia-tap-demo
